LPS-X Add antlr:antlr:2.7.7 back (LPS-144863 removed it) because hibernate 5.6.3.Final depends on it. Otherwise, the error "java.lang.NoClassDefFoundError: antlr.SemanticException" will happen when load com.liferay.shielded.container.internal.ShieldedContainerClassLoader class.